(cl:defpackage deeporange14_msgs-msg
  (:use )
  (:export
   "<BRAKEPRESSURECMD>"
   "BRAKEPRESSURECMD"
   "<MISSIONSTATUS>"
   "MISSIONSTATUS"
   "<MOBILITYMSG>"
   "MOBILITYMSG"
   "<RAPTORSTATEMSG>"
   "RAPTORSTATEMSG"
   "<TORQUECMDSTAMPED>"
   "TORQUECMDSTAMPED"
  ))

