// Generated by gencpp from file deeporange14_msgs/BrakePressureCmd.msg
// DO NOT EDIT!


#ifndef DEEPORANGE14_MSGS_MESSAGE_BRAKEPRESSURECMD_H
#define DEEPORANGE14_MSGS_MESSAGE_BRAKEPRESSURECMD_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace deeporange14_msgs
{
template <class ContainerAllocator>
struct BrakePressureCmd_
{
  typedef BrakePressureCmd_<ContainerAllocator> Type;

  BrakePressureCmd_()
    : header()
    , brkL_cmd(0.0)
    , brkR_cmd(0.0)  {
    }
  BrakePressureCmd_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , brkL_cmd(0.0)
    , brkR_cmd(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _brkL_cmd_type;
  _brkL_cmd_type brkL_cmd;

   typedef double _brkR_cmd_type;
  _brkR_cmd_type brkR_cmd;





  typedef boost::shared_ptr< ::deeporange14_msgs::BrakePressureCmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::deeporange14_msgs::BrakePressureCmd_<ContainerAllocator> const> ConstPtr;

}; // struct BrakePressureCmd_

typedef ::deeporange14_msgs::BrakePressureCmd_<std::allocator<void> > BrakePressureCmd;

typedef boost::shared_ptr< ::deeporange14_msgs::BrakePressureCmd > BrakePressureCmdPtr;
typedef boost::shared_ptr< ::deeporange14_msgs::BrakePressureCmd const> BrakePressureCmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::deeporange14_msgs::BrakePressureCmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::deeporange14_msgs::BrakePressureCmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::deeporange14_msgs::BrakePressureCmd_<ContainerAllocator1> & lhs, const ::deeporange14_msgs::BrakePressureCmd_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.brkL_cmd == rhs.brkL_cmd &&
    lhs.brkR_cmd == rhs.brkR_cmd;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::deeporange14_msgs::BrakePressureCmd_<ContainerAllocator1> & lhs, const ::deeporange14_msgs::BrakePressureCmd_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace deeporange14_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::deeporange14_msgs::BrakePressureCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::deeporange14_msgs::BrakePressureCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::deeporange14_msgs::BrakePressureCmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::deeporange14_msgs::BrakePressureCmd_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::deeporange14_msgs::BrakePressureCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::deeporange14_msgs::BrakePressureCmd_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::deeporange14_msgs::BrakePressureCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8a6c3b4b6c9de0dcdfdf346411efc7fa";
  }

  static const char* value(const ::deeporange14_msgs::BrakePressureCmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8a6c3b4b6c9de0dcULL;
  static const uint64_t static_value2 = 0xdfdf346411efc7faULL;
};

template<class ContainerAllocator>
struct DataType< ::deeporange14_msgs::BrakePressureCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "deeporange14_msgs/BrakePressureCmd";
  }

  static const char* value(const ::deeporange14_msgs::BrakePressureCmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::deeporange14_msgs::BrakePressureCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#Message contains timestamped Brake pressure commands\n"
"Header header\n"
"\n"
"float64 brkL_cmd\n"
"float64 brkR_cmd\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::deeporange14_msgs::BrakePressureCmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::deeporange14_msgs::BrakePressureCmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.brkL_cmd);
      stream.next(m.brkR_cmd);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BrakePressureCmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::deeporange14_msgs::BrakePressureCmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::deeporange14_msgs::BrakePressureCmd_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "brkL_cmd: ";
    Printer<double>::stream(s, indent + "  ", v.brkL_cmd);
    s << indent << "brkR_cmd: ";
    Printer<double>::stream(s, indent + "  ", v.brkR_cmd);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DEEPORANGE14_MSGS_MESSAGE_BRAKEPRESSURECMD_H
