// Generated by gencpp from file deeporange14_msgs/BrakePressure.msg
// DO NOT EDIT!


#ifndef DEEPORANGE14_MSGS_MESSAGE_BRAKEPRESSURE_H
#define DEEPORANGE14_MSGS_MESSAGE_BRAKEPRESSURE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace deeporange14_msgs
{
template <class ContainerAllocator>
struct BrakePressure_
{
  typedef BrakePressure_<ContainerAllocator> Type;

  BrakePressure_()
    : header()
    , brkL_pr(0.0)
    , brkR_pr(0.0)  {
    }
  BrakePressure_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , brkL_pr(0.0)
    , brkR_pr(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _brkL_pr_type;
  _brkL_pr_type brkL_pr;

   typedef double _brkR_pr_type;
  _brkR_pr_type brkR_pr;





  typedef boost::shared_ptr< ::deeporange14_msgs::BrakePressure_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::deeporange14_msgs::BrakePressure_<ContainerAllocator> const> ConstPtr;

}; // struct BrakePressure_

typedef ::deeporange14_msgs::BrakePressure_<std::allocator<void> > BrakePressure;

typedef boost::shared_ptr< ::deeporange14_msgs::BrakePressure > BrakePressurePtr;
typedef boost::shared_ptr< ::deeporange14_msgs::BrakePressure const> BrakePressureConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::deeporange14_msgs::BrakePressure_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::deeporange14_msgs::BrakePressure_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::deeporange14_msgs::BrakePressure_<ContainerAllocator1> & lhs, const ::deeporange14_msgs::BrakePressure_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.brkL_pr == rhs.brkL_pr &&
    lhs.brkR_pr == rhs.brkR_pr;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::deeporange14_msgs::BrakePressure_<ContainerAllocator1> & lhs, const ::deeporange14_msgs::BrakePressure_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace deeporange14_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::deeporange14_msgs::BrakePressure_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::deeporange14_msgs::BrakePressure_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::deeporange14_msgs::BrakePressure_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::deeporange14_msgs::BrakePressure_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::deeporange14_msgs::BrakePressure_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::deeporange14_msgs::BrakePressure_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::deeporange14_msgs::BrakePressure_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a255ffc9ccf37ff061f56bd425f52afa";
  }

  static const char* value(const ::deeporange14_msgs::BrakePressure_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa255ffc9ccf37ff0ULL;
  static const uint64_t static_value2 = 0x61f56bd425f52afaULL;
};

template<class ContainerAllocator>
struct DataType< ::deeporange14_msgs::BrakePressure_<ContainerAllocator> >
{
  static const char* value()
  {
    return "deeporange14_msgs/BrakePressure";
  }

  static const char* value(const ::deeporange14_msgs::BrakePressure_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::deeporange14_msgs::BrakePressure_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#Message contains timestamped Brake pressure commands\n"
"Header header\n"
"\n"
"float64 brkL_pr\n"
"float64 brkR_pr\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::deeporange14_msgs::BrakePressure_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::deeporange14_msgs::BrakePressure_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.brkL_pr);
      stream.next(m.brkR_pr);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BrakePressure_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::deeporange14_msgs::BrakePressure_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::deeporange14_msgs::BrakePressure_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "brkL_pr: ";
    Printer<double>::stream(s, indent + "  ", v.brkL_pr);
    s << indent << "brkR_pr: ";
    Printer<double>::stream(s, indent + "  ", v.brkR_pr);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DEEPORANGE14_MSGS_MESSAGE_BRAKEPRESSURE_H
